services:
  postgres:
    image: postgres:16
    container_name: ledger-postgres
    environment:
      POSTGRES_DB: ledgerdb
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledgerpass
    ports:
      - "5433:5432"   # ⬅️ CAMBIO CLAVE
    volumes:
      - ledger_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger -d ledgerdb"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  ledger_pgdata:
